from langchain_core.messages import HumanMessage
from services.llm_service import generate_answer
from agent.react_agent import agent
from fastapi import FastAPI, UploadFile, File
from services.pdf_service import extract_text
from utils.chunker import chunk_text
from services.embedding_service import generate_embeddings
from database.qdrant import (
    create_collection,
    store_embeddings,
    search_similar_chunks,
    get_documents,
    delete_document,
)

from pydantic import BaseModel
from typing import Optional
import shutil
import os

app = FastAPI()


chat_history = []


class SearchRequest(BaseModel):
    query: str
    filename: Optional[str] = None

UPLOAD_DIR = "uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)


@app.get("/")
def home():
    return {
        "message": "AI Document Assistant API "
    }

@app.get("/documents")
async def documents():

    docs = get_documents()

    return {
        "documents": docs
    }

@app.delete("/documents/{filename}")
async def remove_document(filename: str):

    delete_document(filename)

    return {
        "message": f"{filename} deleted successfully."
    }

@app.on_event("startup")
async def startup():
    create_collection()


@app.post("/upload")
async def upload_pdf(file: UploadFile = File(...)):

    file_path = os.path.join(UPLOAD_DIR, file.filename)

    with open(file_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    # Extract page-wise text
    pages = extract_text(file_path)

    all_chunks = []
    all_metadata = []

    for page in pages:
        chunks = chunk_text(page["text"])

        for chunk in chunks:
            all_chunks.append(chunk)
            all_metadata.append(
                {
                    "page": page["page"]
                }
            )

    embeddings = generate_embeddings(all_chunks)

    store_embeddings(
        all_chunks,
        embeddings,
        file.filename,
        all_metadata
    )

    return {
        "filename": file.filename,
        "pages": len(pages),
        "chunks": len(all_chunks),
        "first_chunk": all_chunks[0] if all_chunks else ""
    }


@app.post("/search")
async def search(request: SearchRequest):

    # Add the user's message to the conversation
    chat_history.append(
        HumanMessage(content=request.query)
    )

    # Send the entire conversation to the agent
    response = agent.invoke(
        {
            "messages": chat_history
        }
    )

    # Save all new messages generated by the agent
    chat_history.extend(
        response["messages"][len(chat_history):]
    )

    answer = response["messages"][-1].content

    return {
        "query": request.query,
        "answer": answer,
    }

@app.get("/documents")
def documents():
    return {
        "documents": get_documents()
    }

@app.delete("/documents/{filename}")
def delete_file(filename: str):
    delete_document(filename)

    return {
        "message": f"{filename} deleted successfully"
    }